server:
  port: 4445

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    protocol: smtps
    host: smtp.mail.ru
    port: 465
    username: trade_test42@mail.ru
    password: 62M8ZcThdpetP3EDmjeH
    properties:
      mail.smtp.auth : true
      mail.smtp.starttls : true

vaadin:
  whitelisted-packages: com/trade_accounting/components

invoice_received_url: api/invoice_received

issued_invoice_url: api/issuedInvoice

prepayment_return_url: api/prepaymentreturn

retail_cloud_check_url: api/cloudcheck

retail_shift_url: api/retailshift

loss_url: api/loss

loss_product_url: api/lossproduct

retail_making_url: api/making

orders_of_production_url: api/orders_of_production

technical_operations_url: api/technical/operations

technical_card_production_url: api/technical/card/production

contact_url: api/contact

base_url: http://localhost:4444

tax_system_url: api/taxsystem

company_url: api/company

currency_url: api/currency

bank_account_url: api/bank/account

bonus_program_url: api/bonusprogram

contractor_group_url: api/contractor/group

contractor_url: api/contractor

role_url: api/role

attribute_calculation_object_url: api/attribute/calculation/object

contract_url: api/contract

department_url: api/department

employee_url: api/employee

image_url: api/image

legal_detail_url: api/legaldetail

position_url: api/position

product_group_url: api/productgroup

product_url: api/product

production_targets_url: api/production_targets

type_of_contractor_url: api/typeofcontractor

type_of_price_url: api/typeofprice

unit_url: api/unit

warehouse_url: api/warehouse

invoice_url: api/invoice

invoices_status_url: api/invoicestatus

buyersReturn_url: api/buyersreturn

invoice_product_url: api/invoice/product

authentication_url: login

project_url: api/project

payment_url: api/payment

retail_sales_url: api/retail_sales

retail_stores_url: api/retail_stores

retail_operation_with_points_url: api/operation_with

revenue_url: api/revenue

contractor_status_url: api/contractor_status

task_url: api/tasks

task_comment_url: api/task_comments

technical_card_url: api/technical_card

technical_card_group_url: api/technical_card_group

remain_url: api/remain

supplier_account_url: api/supplierAccount

address_url: api/address

return_supplier_url: api/returnToSupplier

correction_url: api/correction

correction_product_url: api/correction/product

price_list_url: api/priceList

purchase_control_url: /api/purchasecontrol

moneySubCashFlowUrl_url: api/money

moneySubMutualSettlementsUrl_url: api/mutualSettlements

salesSubGoodsForSaleUrl_url: api/goodsForSale

balance_adjustment_url: api/balanceAdjustment

inventarization_url: api/inventarization

inventarization_product_url: api/inventarization/product

internal_order_url: api/internalorder

internal_order_product_url:  api/internalorder/product

payout_url:  api/payout

acceptance_url: api/acceptance

acceptance_product_url: api/acceptance/product

movement_url:  /api/movement

movement_product_url:  /api/movement/product

moneySubProfitLoss_url: /api/profitloss

productprice_url: /api/productprice

purchase_current_balance_url: /api/purchase_current_balance

purchase_history_of_sales_url: /api/purchasehistory

purchase_forecast_url: /api/purchase_forecast

returns_url: api/returns

retail_points_url: api/operation_with_points

prepayout_url: api/prepayout

operations_url: api/operations

shipment_url: api/shipment

shipment_product_url: api/shipmentproduct

return_amount_by_product_url: api/return-amount-by-product

stage_production_url: api/stagesproduction

technical_process_url: api/technical/process

file_url: /api/file

supplier_account_products_list_url: /api/supplier-account-products-list

audit_url: /api/audit

funnel_url: /api/funnel

serial_numbers_url: /api/serialnumbers
#debug: true
